### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by apg30** [apg30/email_agent#12]
- cycle through different images.

-  centre images and expand to full height of window.

**Comment by apg30** [comment]
back ground images change with time. Looks glitchy and unpleasant. It needs to fade in and out. 
Work to be carried out on 'background' branch.

**Comment by camieac** [comment]
This isn't over yet :worried: . Check [stable deployment](http://www2.macs.hw.ac.uk/~cac30/) and you'll see why. The image URIs don't work :scream:

**Comment by apg30** [comment]
There should be the ability to turn this off in settings. Users may not want to download 12 background images.

**Comment by apg30** [comment]
The images vanish then reappear once fully loaded (just before the next one fades in)
